version: '3.8'
services:
  api:
    container_name: Auth_api
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    restart: always
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - authApiNet
    command: npm run start
  database:
    container_name: postgreSQL
    build:
      dockerfile: ./database/Dockerfile
      context: .
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_HOST_PORT}:${PG_CONTAINER_PORT}
    networks:
      - authApiNet
volumes:
  node_modules:
  postgres_data:
networks:
  authApiNet:
    name: authApiNet
    driver: bridge